### ISSUE TITLE
Looking for Front End Support 🔨

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/casa-jobs#6]
Hey folks, we're looking for front end engineers to help Techqueria build out our internal job board. The tech stack is going to be React with Django/Flask backend.

**Comment by caio-davi** [comment]
I have some experience with flask and react (and using both together...), and I'd like to help. 
I noticed the frontend is just the default `creat-react-app` stuff yet. Do you guys already have any plans about the data schemas, API's endpoints, frontend views, etc?
I'm comfortable working both at back and front end...

**Comment by AngelAlvarado** [comment]
@caio-davi ,

We would love your help! Take a look at https://github.com/techqueria/casa-jobs/wiki you'll find some of that information. @fvcproductions is still working on the frontend views/mockups so that'll be ready soon. We'll get back to you with more details ASAP.
